apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Values.manager }}
    app.kubernetes.io/created-by: {{ .Values.author }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/managed-by: {{ .Values.manager }}
        app.kubernetes.io/created-by: {{ .Values.author }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: http
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: http
