apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: nginxdemos/hello:latest
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 3000
          protocol: TCP