apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}

