apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-configmap"
  namespace: "{{ .Values.namespace }}"
data:
  index.html: |
    <html>
    <h1>Caio's Sample Page</h1>
    <p>For some reason, my pods can't pull the nginxdemos/hello image, so I'm using nginx:alpine with a sample page provided from a ConfigMap.<p>
    </html>