apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: "{{ .Values.name }}-namespace"
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
   -  protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}

